name = "Rolling"
uuid = "444271a7-5434-4a02-b82b-0e30a9223c60"
authors = ["Thomas Gillam <tpgillam@googlemail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
